import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const services = [
  {
    title: "Architectural Glass & Glazing",
    description: "Premium architectural glass solutions for commercial, residential, and industrial buildings.",
    icon: "Building2",
    glow: "rgba(59,130,246,0.15)",
    accent: "#3B82F6",
    overview: "Architectural glass and glazing solutions designed to enhance building aesthetics, functionality, and energy efficiency. We deliver high-quality facade systems, storefront glazing, and customized glass installations for modern commercial and residential projects.",
    specs: ["Toughened Glass", "Laminated Glass", "Double Glazed Units", "UV Protection", "Thermal Insulation", "Weather Resistance"],
    features: ["Modern Appearance", "Energy Efficient", "Natural Lighting", "Durable Construction", "Low Maintenance", "Custom Designs"],
    applications: ["Commercial Buildings", "Shopping Malls", "Corporate Offices", "Hotels", "Hospitals", "Luxury Homes"],
  },
  {
    title: "Structural Glazing Works",
    description: "Frameless structural glazing systems for modern and elegant building facades.",
    icon: "Layers",
    glow: "rgba(16,185,129,0.15)",
    accent: "#10B981",
    overview: "Structural glazing systems create seamless glass facades with minimal visible framing. Engineered for durability, safety, and aesthetics, these systems are ideal for modern commercial buildings requiring premium architectural appeal.",
    specs: ["Structural Silicone", "Toughened Glass", "Wind Load Resistance", "UV Stability", "Weather Sealing", "Steel Supports"],
    features: ["Frameless Look", "Premium Appearance", "Enhanced Visibility", "Durable Structure", "Weather Resistant", "Long Lifespan"],
    applications: ["Corporate Offices", "Shopping Malls", "Hotels", "Airports", "Commercial Complexes", "Showrooms"],
  },
  {
    title: "Spider Glazing Systems",
    description: "Advanced spider glazing solutions for transparent architectural facades.",
    icon: "Network",
    glow: "rgba(234,179,8,0.15)",
    accent: "#EAB308",
    overview: "Spider glazing systems use stainless steel spider fittings to support glass panels while maintaining maximum transparency. Perfect for premium commercial projects requiring modern and visually impressive facades.",
    specs: ["Spider Fittings", "Stainless Steel Hardware", "Toughened Glass", "High Transparency", "Structural Support", "Weather Protection"],
    features: ["Minimal Framework", "Premium Finish", "Maximum Visibility", "Modern Design", "Durable Components", "Custom Engineering"],
    applications: ["Showrooms", "Corporate Entrances", "Airports", "Hotels", "Shopping Centers", "Commercial Buildings"],
  },
  {
    title: "Architectural Glass Fixing",
    description: "Professional architectural glass fixing services with precision installation.",
    icon: "Hammer",
    glow: "rgba(249,115,22,0.15)",
    accent: "#F97316",
    overview: "Expert glass fixing solutions for commercial and residential projects using high-quality fittings and installation techniques. Ensures durability, safety, and a flawless architectural finish.",
    specs: ["Glass Anchors", "Steel Fittings", "Weatherproof Installation", "Safety Standards", "Precision Alignment", "Custom Fixing Systems"],
    features: ["Secure Installation", "Long Lifespan", "Professional Finish", "High Safety", "Durable Hardware", "Quality Assurance"],
    applications: ["Commercial Buildings", "Homes", "Offices", "Hotels", "Retail Stores", "Showrooms"],
  },
  {
    title: "Toughened Glass Installations",
    description: "Strong and safe toughened glass installations for modern spaces.",
    icon: "Shield",
    glow: "rgba(239,68,68,0.15)",
    accent: "#EF4444",
    overview: "Premium toughened glass installations offering superior strength, impact resistance, and safety. Suitable for facades, doors, partitions, railings, and interior applications.",
    specs: ["Heat Treated Glass", "Impact Resistance", "Safety Certified", "Thermal Strength", "Scratch Resistant", "Long Durability"],
    features: ["High Strength", "Safe Usage", "Modern Look", "Low Maintenance", "Versatile Application", "Long Lasting"],
    applications: ["Glass Doors", "Partitions", "Facades", "Railings", "Commercial Interiors", "Residential Projects"],
  },
  {
    title: "Glass Partitions",
    description: "Modern glass partition systems for professional and stylish interiors.",
    icon: "PanelsTopLeft",
    glow: "rgba(99,102,241,0.15)",
    accent: "#6366F1",
    overview: "Elegant glass partition solutions that create functional spaces while maintaining openness and natural light. Ideal for offices, conference rooms, clinics, and commercial interiors.",
    specs: ["Toughened Glass", "Frameless Design", "Frosted Glass Options", "Aluminum Profiles", "Acoustic Options", "Easy Maintenance"],
    features: ["Space Optimization", "Modern Design", "Natural Light", "Flexible Layout", "Professional Appearance", "Easy Cleaning"],
    applications: ["Corporate Offices", "Conference Rooms", "Clinics", "Retail Stores", "Educational Institutions", "Commercial Interiors"],
  },
  {
    title: "Toilet Glass Partitions",
    description: "Stylish and durable glass partitions for modern washroom spaces.",
    icon: "DoorOpen",
    glow: "rgba(6,182,212,0.15)",
    accent: "#06B6D4",
    overview: "Custom toilet glass partitions designed for privacy, durability, and aesthetics. Manufactured using high-quality toughened glass and premium hardware.",
    specs: ["Frosted Glass", "Water Resistant", "Stainless Steel Hardware", "Easy Cleaning", "Safety Glass", "Custom Sizes"],
    features: ["Elegant Design", "Privacy", "Moisture Resistant", "Long Lifespan", "Easy Maintenance", "Premium Finish"],
    applications: ["Hotels", "Offices", "Restaurants", "Shopping Malls", "Hospitals", "Residential Bathrooms"],
  },
  {
    title: "ACP Cladding Works",
    description: "Premium ACP cladding solutions for attractive and durable exteriors.",
    icon: "LayoutPanelTop",
    glow: "rgba(168,85,247,0.15)",
    accent: "#A855F7",
    overview: "ACP cladding enhances exterior appearance while providing weather protection and insulation. Available in various finishes and designs suitable for commercial and residential projects.",
    specs: ["Aluminium Composite Panels", "UV Resistant", "Fire Resistant Options", "Weather Protection", "Thermal Insulation", "Lightweight Construction"],
    features: ["Modern Facade", "Durability", "Custom Finishes", "Low Maintenance", "Weather Resistance", "Cost Effective"],
    applications: ["Commercial Buildings", "Shopping Malls", "Hospitals", "Hotels", "Showrooms", "Corporate Offices"],
  },
  {
    title: "3D Elevation Works",
    description: "Creative 3D elevation designs that enhance building appearance.",
    icon: "Building",
    glow: "rgba(244,114,182,0.15)",
    accent: "#F472B6",
    overview: "Modern 3D elevation solutions that create visually striking building exteriors. Customized according to architectural requirements and project aesthetics.",
    specs: ["Custom Designs", "Exterior Finishes", "Architectural Detailing", "Weather Resistant Materials", "Premium Appearance", "Long Durability"],
    features: ["Unique Look", "Enhanced Curb Appeal", "Custom Design", "Modern Style", "Professional Finish", "Premium Materials"],
    applications: ["Homes", "Commercial Buildings", "Showrooms", "Villas", "Hotels", "Office Buildings"],
  },
  {
    title: "Commercial Exterior Solutions",
    description: "Comprehensive exterior solutions for modern commercial properties.",
    icon: "Landmark",
    glow: "rgba(34,197,94,0.15)",
    accent: "#22C55E",
    overview: "End-to-end commercial exterior solutions including glazing, cladding, facade systems, and architectural enhancements for commercial developments.",
    specs: ["Facade Systems", "Structural Support", "Weather Protection", "Premium Materials", "Energy Efficiency", "Custom Engineering"],
    features: ["Complete Solution", "Modern Design", "Durability", "High Quality", "Customizable", "Professional Installation"],
    applications: ["Corporate Offices", "Shopping Malls", "Hospitals", "Hotels", "Educational Institutions", "Commercial Complexes"],
  },
  {
    title: "Glass Roofing",
    description: "Elegant glass roofing systems that maximize natural light and modern aesthetics.",
    icon: "Warehouse",
    glow: "rgba(59,130,246,0.15)",
    accent: "#0EA5E9",
    overview: "Glass roofing systems provide a sophisticated solution for bringing natural daylight into interior spaces while maintaining protection from weather conditions. Our customized glass roof installations use premium toughened and laminated glass supported by durable structural frameworks. These systems enhance aesthetics, improve energy efficiency, and create visually stunning architectural spaces for residential, commercial, and hospitality projects.",
    specs: ["Toughened Glass", "Laminated Glass", "UV Protection", "Waterproof Sealing", "Steel Support Structure", "Thermal Insulation"],
    features: ["Natural Daylight", "Modern Design", "Weather Protection", "Energy Efficiency", "Custom Configurations", "Durable Construction"],
    applications: ["Commercial Buildings", "Shopping Malls", "Hotels", "Luxury Homes", "Restaurants", "Atriums"],
  },
  {
    title: "Glass Canopy Works",
    description: "Stylish glass canopy installations for entrances, walkways, and building facades.",
    icon: "Umbrella",
    glow: "rgba(14,165,233,0.15)",
    accent: "#0284C7",
    overview: "Glass canopy systems offer protection from sun and rain while enhancing the visual appeal of building entrances and outdoor spaces. Our canopies are engineered with premium toughened glass and corrosion-resistant support structures to ensure safety, durability, and long-term performance.",
    specs: ["Toughened Glass", "Stainless Steel Supports", "UV Resistant", "Weatherproof Design", "Safety Standards", "Custom Sizes"],
    features: ["Elegant Entrance", "Weather Protection", "Durable Hardware", "Modern Appearance", "Low Maintenance", "Custom Design"],
    applications: ["Building Entrances", "Hotels", "Offices", "Shopping Centers", "Showrooms", "Hospitals"],
  },
  {
    title: "Pergola Glass Fittings",
    description: "Premium pergola glass solutions for outdoor comfort and architectural beauty.",
    icon: "Trees",
    glow: "rgba(34,197,94,0.15)",
    accent: "#16A34A",
    overview: "Pergola glass fittings combine outdoor functionality with modern design. We install durable glass panels and support systems that create elegant outdoor spaces while providing protection from weather elements. Ideal for terraces, patios, resorts, and commercial outdoor seating areas.",
    specs: ["Toughened Glass", "Weatherproof Materials", "Steel Framework", "UV Protection", "Custom Fittings", "Corrosion Resistance"],
    features: ["Outdoor Comfort", "Premium Appearance", "Weather Resistant", "Long Lifespan", "Custom Designs", "Easy Maintenance"],
    applications: ["Resorts", "Terraces", "Restaurants", "Hotels", "Outdoor Cafes", "Luxury Villas"],
  },
  {
    title: "Glass Handrails",
    description: "Modern glass handrail systems offering safety without compromising visibility.",
    icon: "Fence",
    glow: "rgba(99,102,241,0.15)",
    accent: "#4F46E5",
    overview: "Glass handrails provide a sleek and contemporary safety solution for staircases, balconies, terraces, and commercial spaces. Manufactured using toughened safety glass and premium hardware, these systems deliver unobstructed views, durability, and architectural elegance.",
    specs: ["Toughened Safety Glass", "Stainless Steel Hardware", "Impact Resistance", "Weather Resistant", "Custom Heights", "Secure Mounting"],
    features: ["Unobstructed Views", "Modern Design", "High Safety", "Low Maintenance", "Durable Construction", "Premium Finish"],
    applications: ["Balconies", "Staircases", "Terraces", "Hotels", "Commercial Buildings", "Luxury Homes"],
  },
  {
    title: "Patch Fittings",
    description: "High-quality patch fitting systems for frameless glass doors and partitions.",
    icon: "Wrench",
    glow: "rgba(249,115,22,0.15)",
    accent: "#EA580C",
    overview: "Patch fittings are essential components used in frameless glass doors and partition systems. We provide premium-grade stainless steel patch fittings designed for smooth operation, durability, and a clean architectural appearance in commercial and residential environments.",
    specs: ["Stainless Steel Construction", "Corrosion Resistance", "Heavy Duty Design", "Precision Engineering", "Glass Compatibility", "Long Lifespan"],
    features: ["Smooth Operation", "Premium Finish", "Strong Support", "Durable Hardware", "Modern Appearance", "Reliable Performance"],
    applications: ["Glass Doors", "Office Partitions", "Showrooms", "Hotels", "Commercial Interiors", "Retail Stores"],
  },
  {
    title: "LED Letter Boards",
    description: "Eye-catching LED signage solutions for branding and business visibility.",
    icon: "BadgeInfo",
    glow: "rgba(250,204,21,0.15)",
    accent: "#EAB308",
    overview: "LED letter boards provide bright and attractive signage solutions that improve brand visibility and customer engagement. Our custom LED signboards are designed for durability, energy efficiency, and maximum impact in commercial environments.",
    specs: ["LED Illumination", "Weatherproof Construction", "Energy Efficient", "Custom Fonts", "High Visibility", "Long Lifespan"],
    features: ["Brand Promotion", "Bright Display", "Low Power Consumption", "Custom Designs", "Outdoor Durability", "Professional Appearance"],
    applications: ["Retail Stores", "Showrooms", "Hospitals", "Hotels", "Restaurants", "Corporate Offices"],
  },
  {
    title: "V Board Partition Works",
    description: "Functional partition systems for efficient interior space management.",
    icon: "PanelsLeftBottom",
    glow: "rgba(168,85,247,0.15)",
    accent: "#9333EA",
    overview: "V Board partition systems offer cost-effective and durable solutions for dividing interior spaces. Designed for commercial, office, and institutional environments, these partitions provide flexibility, privacy, and efficient space utilization.",
    specs: ["Lightweight Panels", "Moisture Resistance", "Easy Installation", "Durable Finish", "Custom Dimensions", "Low Maintenance"],
    features: ["Space Optimization", "Affordable Solution", "Quick Installation", "Flexible Layouts", "Professional Appearance", "Long Durability"],
    applications: ["Corporate Offices", "Educational Institutions", "Clinics", "Commercial Spaces", "Warehouses", "Retail Outlets"],
  },
  {
    title: "MS Structural Works",
    description: "Robust mild steel structural fabrication and installation services.",
    icon: "Construction",
    glow: "rgba(239,68,68,0.15)",
    accent: "#DC2626",
    overview: "MS Structural Works include fabrication and installation of mild steel structures used in commercial, industrial, and architectural projects. Our experienced team delivers strong, reliable, and precisely engineered steel frameworks that serve as the foundation for various construction applications.",
    specs: ["Mild Steel Fabrication", "Structural Welding", "Corrosion Protection", "Load Bearing Design", "Custom Engineering", "Industrial Standards"],
    features: ["High Strength", "Durable Framework", "Custom Fabrication", "Reliable Performance", "Professional Installation", "Long Service Life"],
    applications: ["Industrial Buildings", "Commercial Projects", "Factories", "Warehouses", "Canopy Structures", "Steel Frameworks"],
  },
];

async function main() {
  console.log("Seeding services...");

  // Clear existing services first to avoid duplicates on re-run
  await prisma.service.deleteMany();

  for (const s of services) {
    await prisma.service.create({
      data: {
        title: s.title,
        description: s.description,
        icon: s.icon,
        glow: s.glow,
        accent: s.accent,
        overview: s.overview,
        specs: JSON.stringify(s.specs),
        features: JSON.stringify(s.features),
        applications: JSON.stringify(s.applications),
      },
    });
  }

  console.log(`✅ Seeded ${services.length} services.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
